### ISSUE TITLE
Accelix issue

### ISSUE THREAD

**Issue by 1nsertTextHere** [lukawarren/Lorien-Legacies#75] opened 2020-04-23 16:13 UTC
Not really an issue, but you loose stamina when accelix is active, not when it is being used. I feel like stamina should only deplete when you are moving with accelix and it regenerates when you arent. Also you loose and gain stamina way, way too quickly, like one second depleted, one second restored.

**Comment by 1nsertTextHere** [comment] 2020-12-24 16:08
also, when fixing, take into consideration issue #85

**Comment by lukawarren** [comment] 2021-01-28 15:51
Duplicate of #96

**Closed as completed by lukawarren** 2021-01-28 15:51 UTC
