### ISSUE TITLE
Stamina issue

### ISSUE THREAD

**Issue by 1nsertTextHere** [lukawarren/Lorien-Legacies#76] opened 2020-04-23 16:17 UTC
I have found that you loose stamina way too quickly. You also gain it too quickly. And it depletes when toggle able legacies (Avex, Fortem, Accelix, etc.) are set to active, even when you arent doing anything. But you dont loose stamina for legacies like Glacien when you put down ice.

**Comment by lukawarren** [comment] 2020-06-02 08:58
Duplicate of #91

**Closed as completed by lukawarren** 2020-06-02 08:58 UTC
